version: '2'

services:

  mongodb:
    image: mongo
    container_name: mongodb

    ports:
      - "27017:27017"

  cli:
    build: .
    container_name: anecdote-cli

    depends_on:
      - mongodb

    volumes:
      - "./:/app"